// <auto-generated />
using System;
using DACS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DACS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DACS.Models.ChiTietHopDong", b =>
                {
                    b.Property<int>("IdPhuongTien")
                        .HasColumnType("int");

                    b.Property<int>("IdHopDong")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaThue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("HopDongIdHopDong")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayThue")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayTra")
                        .HasColumnType("date");

                    b.Property<int>("PhuongTienIdPhuongTien")
                        .HasColumnType("int");

                    b.HasKey("IdPhuongTien", "IdHopDong");

                    b.HasIndex("HopDongIdHopDong");

                    b.HasIndex("PhuongTienIdPhuongTien");

                    b.ToTable("ChiTietHopDongs");
                });

            modelBuilder.Entity("DACS.Models.ChiTietQuyen", b =>
                {
                    b.Property<int>("IdChucVu")
                        .HasColumnType("int");

                    b.Property<int>("IdQuyen")
                        .HasColumnType("int");

                    b.Property<int>("ChucVuIdChucVu")
                        .HasColumnType("int");

                    b.Property<int>("QuyenIdQuyen")
                        .HasColumnType("int");

                    b.HasKey("IdChucVu", "IdQuyen");

                    b.HasIndex("ChucVuIdChucVu");

                    b.HasIndex("QuyenIdQuyen");

                    b.ToTable("ChiTietQuyens");
                });

            modelBuilder.Entity("DACS.Models.ChiTietViPham", b =>
                {
                    b.Property<int>("IdPhieuViPham")
                        .HasColumnType("int");

                    b.Property<int>("IdQuyDinh")
                        .HasColumnType("int");

                    b.Property<int>("PhieuViPhamIdPhieuViPham")
                        .HasColumnType("int");

                    b.Property<int>("QuyDinhIdQuyDinh")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianXayRa")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPhieuViPham", "IdQuyDinh");

                    b.HasIndex("PhieuViPhamIdPhieuViPham");

                    b.HasIndex("QuyDinhIdQuyDinh");

                    b.ToTable("ChiTietViPhams");
                });

            modelBuilder.Entity("DACS.Models.ChucVu", b =>
                {
                    b.Property<int>("IdChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChucVu"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdChucVu");

                    b.ToTable("ChucVus");
                });

            modelBuilder.Entity("DACS.Models.DuLieuGPS", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("HanhTrinhIdHanhTrinh")
                        .HasColumnType("int");

                    b.Property<int>("IdHanhTrinh")
                        .HasColumnType("int");

                    b.Property<decimal>("KinhDo")
                        .HasColumnType("decimal(11, 8)");

                    b.Property<int?>("ThietBiGPSIdThietBi")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TocDo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ViDo")
                        .HasColumnType("decimal(11, 8)");

                    b.HasKey("Id");

                    b.HasIndex("HanhTrinhIdHanhTrinh");

                    b.HasIndex("ThietBiGPSIdThietBi");

                    b.ToTable("DuLieuGPS");
                });

            modelBuilder.Entity("DACS.Models.HanhTrinh", b =>
                {
                    b.Property<int>("IdHanhTrinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHanhTrinh"));

                    b.Property<int>("IdPhuongTien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDi")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhuongTienIdPhuongTien")
                        .HasColumnType("int");

                    b.Property<decimal>("TongQuangDuong")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdHanhTrinh");

                    b.HasIndex("PhuongTienIdPhuongTien");

                    b.ToTable("HanhTrinhs");
                });

            modelBuilder.Entity("DACS.Models.HopDong", b =>
                {
                    b.Property<int>("IdHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHopDong"));

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("KhachHangMaCccd")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaCccd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("NgayTao")
                        .HasColumnType("date");

                    b.Property<int>("TaiKhoanIdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdHopDong");

                    b.HasIndex("KhachHangMaCccd");

                    b.HasIndex("TaiKhoanIdTaiKhoan");

                    b.ToTable("HopDongs");
                });

            modelBuilder.Entity("DACS.Models.KhachHang", b =>
                {
                    b.Property<string>("MaCccd")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCccd");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("DACS.Models.PhieuViPham", b =>
                {
                    b.Property<int>("IdPhieuViPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPhieuViPham"));

                    b.Property<int>("HanhTrinhIdHanhTrinh")
                        .HasColumnType("int");

                    b.Property<int>("IdHanhTrinh")
                        .HasColumnType("int");

                    b.Property<string>("KhachHangMaCccd")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaCccd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayViPham")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienPhat")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdPhieuViPham");

                    b.HasIndex("HanhTrinhIdHanhTrinh");

                    b.HasIndex("KhachHangMaCccd");

                    b.ToTable("PhieuViPhams");
                });

            modelBuilder.Entity("DACS.Models.PhuongTien", b =>
                {
                    b.Property<int>("IdPhuongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPhuongTien"));

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HangSanXuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdThietBi")
                        .HasColumnType("int");

                    b.Property<string>("LoaiPhuongTien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThietBiGPSIdThietBi")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdPhuongTien");

                    b.HasIndex("BienSo")
                        .IsUnique();

                    b.HasIndex("ThietBiGPSIdThietBi");

                    b.ToTable("PhuongTiens");
                });

            modelBuilder.Entity("DACS.Models.QuyDinh", b =>
                {
                    b.Property<int>("IdQuyDinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuyDinh"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MucPhat")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TenQuyDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdQuyDinh");

                    b.ToTable("QuyDinhs");
                });

            modelBuilder.Entity("DACS.Models.Quyen", b =>
                {
                    b.Property<int>("IdQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuyen"));

                    b.Property<string>("MaQuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdQuyen");

                    b.ToTable("Quyens");
                });

            modelBuilder.Entity("DACS.Models.TaiKhoan", b =>
                {
                    b.Property<int>("IdTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTaiKhoan"));

                    b.Property<int>("ChucVuIdChucVu")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdChucVu")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTaiKhoan");

                    b.HasIndex("ChucVuIdChucVu");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("DACS.Models.ThietBiGPS", b =>
                {
                    b.Property<int>("IdThietBi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThietBi"));

                    b.Property<string>("LoaiThietBi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaImei")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("NgayKichHoat")
                        .HasColumnType("date");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdThietBi");

                    b.HasIndex("MaImei")
                        .IsUnique();

                    b.ToTable("ThietBiGPS");
                });

            modelBuilder.Entity("DACS.Models.ChiTietHopDong", b =>
                {
                    b.HasOne("DACS.Models.HopDong", "HopDong")
                        .WithMany("ChiTietHopDongs")
                        .HasForeignKey("HopDongIdHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DACS.Models.PhuongTien", "PhuongTien")
                        .WithMany("ChiTietHopDongs")
                        .HasForeignKey("PhuongTienIdPhuongTien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");

                    b.Navigation("PhuongTien");
                });

            modelBuilder.Entity("DACS.Models.ChiTietQuyen", b =>
                {
                    b.HasOne("DACS.Models.ChucVu", "ChucVu")
                        .WithMany("ChiTietQuyen")
                        .HasForeignKey("ChucVuIdChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DACS.Models.Quyen", "Quyen")
                        .WithMany("ChiTietQuyens")
                        .HasForeignKey("QuyenIdQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("DACS.Models.ChiTietViPham", b =>
                {
                    b.HasOne("DACS.Models.PhieuViPham", "PhieuViPham")
                        .WithMany("ChiTietViPhams")
                        .HasForeignKey("PhieuViPhamIdPhieuViPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DACS.Models.QuyDinh", "QuyDinh")
                        .WithMany("ChiTietViPhams")
                        .HasForeignKey("QuyDinhIdQuyDinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuViPham");

                    b.Navigation("QuyDinh");
                });

            modelBuilder.Entity("DACS.Models.DuLieuGPS", b =>
                {
                    b.HasOne("DACS.Models.HanhTrinh", "HanhTrinh")
                        .WithMany("DuLieuGPS")
                        .HasForeignKey("HanhTrinhIdHanhTrinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DACS.Models.ThietBiGPS", null)
                        .WithMany("DuLieuGPS")
                        .HasForeignKey("ThietBiGPSIdThietBi");

                    b.Navigation("HanhTrinh");
                });

            modelBuilder.Entity("DACS.Models.HanhTrinh", b =>
                {
                    b.HasOne("DACS.Models.PhuongTien", "PhuongTien")
                        .WithMany("HanhTrinhs")
                        .HasForeignKey("PhuongTienIdPhuongTien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhuongTien");
                });

            modelBuilder.Entity("DACS.Models.HopDong", b =>
                {
                    b.HasOne("DACS.Models.KhachHang", "KhachHang")
                        .WithMany("HopDongs")
                        .HasForeignKey("KhachHangMaCccd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DACS.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("HopDongs")
                        .HasForeignKey("TaiKhoanIdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DACS.Models.PhieuViPham", b =>
                {
                    b.HasOne("DACS.Models.HanhTrinh", "HanhTrinh")
                        .WithMany("PhieuViPhams")
                        .HasForeignKey("HanhTrinhIdHanhTrinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DACS.Models.KhachHang", "KhachHang")
                        .WithMany("PhieuViPhams")
                        .HasForeignKey("KhachHangMaCccd");

                    b.Navigation("HanhTrinh");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("DACS.Models.PhuongTien", b =>
                {
                    b.HasOne("DACS.Models.ThietBiGPS", "ThietBiGPS")
                        .WithMany("PhuongTiens")
                        .HasForeignKey("ThietBiGPSIdThietBi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThietBiGPS");
                });

            modelBuilder.Entity("DACS.Models.TaiKhoan", b =>
                {
                    b.HasOne("DACS.Models.ChucVu", "ChucVu")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("ChucVuIdChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("DACS.Models.ChucVu", b =>
                {
                    b.Navigation("ChiTietQuyen");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("DACS.Models.HanhTrinh", b =>
                {
                    b.Navigation("DuLieuGPS");

                    b.Navigation("PhieuViPhams");
                });

            modelBuilder.Entity("DACS.Models.HopDong", b =>
                {
                    b.Navigation("ChiTietHopDongs");
                });

            modelBuilder.Entity("DACS.Models.KhachHang", b =>
                {
                    b.Navigation("HopDongs");

                    b.Navigation("PhieuViPhams");
                });

            modelBuilder.Entity("DACS.Models.PhieuViPham", b =>
                {
                    b.Navigation("ChiTietViPhams");
                });

            modelBuilder.Entity("DACS.Models.PhuongTien", b =>
                {
                    b.Navigation("ChiTietHopDongs");

                    b.Navigation("HanhTrinhs");
                });

            modelBuilder.Entity("DACS.Models.QuyDinh", b =>
                {
                    b.Navigation("ChiTietViPhams");
                });

            modelBuilder.Entity("DACS.Models.Quyen", b =>
                {
                    b.Navigation("ChiTietQuyens");
                });

            modelBuilder.Entity("DACS.Models.TaiKhoan", b =>
                {
                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("DACS.Models.ThietBiGPS", b =>
                {
                    b.Navigation("DuLieuGPS");

                    b.Navigation("PhuongTiens");
                });
#pragma warning restore 612, 618
        }
    }
}
